Add missing ESPHome for home automaction
selfhostedshow/wiki pull request #102
Opened 2021-02-12 11:25 UTC by cooljimy84

Hope this helps as i use ESPHome more than tasmota on my devices

2021-02-12 11:37 UTC, RealOrangeOne submitted a review, later dismissed

2021-02-12 12:37 UTC, py-crash requested changes

2021-02-12 12:37 UTC, py-crash commented on docs/home-automation/ESPHome/index.md
> +## Introduction
White line missing

2021-02-12 12:37 UTC, py-crash commented on docs/home-automation/ESPHome/index.md
> +* Flashing over serial.
Reapeated information

2021-02-12 14:48 UTC, cooljimy84 commented
Sorry, bit of a Github noob here,

2022-05-02 13:36 UTC, ironicbadger commented
#118

2022-05-02 13:36 UTC, closed without merging